FROM node:20-alpine AS build
WORKDIR /app
COPY graphql-server/package.json ./
RUN npm install
COPY graphql-server/tsconfig.json ./
COPY graphql-server/src ./src
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY graphql-server/package.json ./
RUN npm install --omit=dev
COPY --from=build /app/dist ./dist
COPY db ./db
EXPOSE 4000
CMD ["node", "dist/index.js"]
